version: "3.8"

services:
  postgres:
    image: postgres:13.0
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=public
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  shortener:
    depends_on: 
      - postgres
    build: .
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASS: password
      DB_NAME: public
    ports:
      - 8080:8080

volumes: 
  postgres: {}